Algoritmo "EXERCICIO_4_K_PAG_42"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos 
// Descrição   : ler um valor inteiro e informar se ele não for maior que 3
// Autor(a)    : Grazielly Raissa Pereira De Souza
// Data atual  : 08/04/2024
Var
   numero:inteiro
Inicio
   Escreva("Digite um numero inteiro: ")
   leia(numero)


   se numero <= 3 entao
      Escreva("O numero digitado foi:",numero)
   fimse



Fimalgoritmo
