Algoritmo "QuadradoNumeros_Manzano"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exibir o quadrado dos números inteiros de 15 a 200
// Autor(a)    : Grazielly Raissa Pereira De Souza
// Data atual  : 13/04/2024
Var
contadora, resultado: inteiro

Inicio
   para contadora de 15 ate 200 passo 1 faca
      resultado <- contadora * contadora
      escreval(contadora, " ^ 2 =", resultado)
   fimpara

Fimalgoritmo
