Algoritmo "20Impares"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Informa e exibir os números ímpares de 1 até 20
// Autor(a)    : Grazielly Raissa Pereira De Souza
// Data atual  : 15/04/2024
Var
   contadora: inteiro

Inicio
   para contadora de 1 ate 20 passo 1 faca

      se contadora % 2 = 1 entao
         escreval ("Números ímpares de 1 até 20:", contadora)
      fimse

   fimpara

Fimalgoritmo
